-- Atomic relational core of the public Job Application workflow (approved
-- architecture §7 / amendment 7).
--
-- This is a single function call, so find-or-create-Candidate + create-Application can
-- never leave half-created state the way a sequence of independent client calls could.
--
-- SECURITY DEFINER + fixed search_path so the function's own privilege is sufficient
-- regardless of future grant changes; EXECUTE is revoked from every client-reachable
-- role below and granted only to service_role, so the public browser can never call
-- this directly even if it discovered the function name — only the trusted Next.js
-- server endpoint (using the service-role client) may invoke it.
--
-- Storage upload is explicitly NOT part of this function (cannot share a Postgres
-- transaction with a Storage API call) — the server endpoint handles that separately,
-- and is responsible for its own failure-cleanup handling when the website is wired up.
--
-- Status, owner, and reference are never accepted as input: initial status is always
-- 'new', initial ownership is always NULL (Unassigned), and references are always
-- generated by the set_reference() trigger — none of this is trusted from the caller.
create or replace function submit_public_application(
  p_job_reference text,
  p_full_name text,
  p_email text,
  p_phone text,
  p_location text default null,
  p_sector_id uuid default null,
  p_source text default 'Website'
)
returns table (
  candidate_id uuid,
  candidate_reference text,
  application_id uuid,
  application_reference text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email_normalized text := lower(trim(p_email));
  v_job jobs%rowtype;
  v_candidate_id uuid;
  v_candidate_reference text;
  v_application_id uuid;
  v_application_reference text;
begin
  if p_full_name is null or btrim(p_full_name) = '' then
    raise exception 'p_full_name is required';
  end if;
  if v_email_normalized is null or v_email_normalized = '' then
    raise exception 'p_email is required';
  end if;

  select * into v_job
  from jobs
  where reference = p_job_reference
    and status = 'open'
    and publish_on_website
    and archived_at is null;

  if not found then
    raise exception 'Job % is not open for applications', p_job_reference;
  end if;

  select id, reference into v_candidate_id, v_candidate_reference
  from candidates
  where email_normalized = v_email_normalized;

  if not found then
    insert into candidates (full_name, email, phone, location, primary_sector_id, registration_source, owner_id)
    values (p_full_name, p_email, p_phone, p_location, p_sector_id, coalesce(p_source, 'Website'), null)
    returning id, reference into v_candidate_id, v_candidate_reference;
  end if;

  insert into applications (candidate_id, job_id, owner_id, status, source, submitted_at)
  values (v_candidate_id, v_job.id, null, 'new', coalesce(p_source, 'Website'), now())
  returning id, reference into v_application_id, v_application_reference;

  return query select v_candidate_id, v_candidate_reference, v_application_id, v_application_reference;
exception
  when unique_violation then
    raise exception 'This candidate has already applied for this job';
end;
$$;

revoke all on function submit_public_application from public;
revoke all on function submit_public_application from anon, authenticated;
grant execute on function submit_public_application to service_role;
